### ISSUE TITLE
Identify scrips that convert THEMIS radiance to temperature

### ISSUE THREAD

**Issue by rfergason** [USGS-Astrogeology/themis_ra#17]
As a user, I want to identify existing scripts that convert THEMIS radiance to temperature (and vice versa), so that I can correctly calculate surface temperature.

Algorithms to convert THEMIS temperature to radiance (and vice versa) have been provided by the THEMIS team and are operated in 'davinci'. Davinci is installed on the astrovm machines and the cluster. Robin can provide the individual algorithms.  The algorithm can be applied to all bands in a THEMIS image, or to any individual band.   May need to import the THEMIS instrument response function (or it may be hard-coded in the algorithm).

- [x] @ rfergason provide individual algorithm location and needed inputs

**Comment by rfergason** [comment]
The script to convert THEMIS radiance to temperature (and vice versa) is the davinci script rad3tb and the code is located in:
/usgs/apps/davinci/2.17/share/davinci/library/themis_science.dvrc

Code requires temp_rad_vn look-up table ($DV_SCRIPT_FILES+"/instrument_parameters/temp_rad_v4").
Code calls radtotb to do most of the work.

----------  Code is copied below.  This may be more than you want....

define rad3tb() {
#Added instrument_parameters to $DV_SCRIPT_FILES support - 1-30-09

if ($ARGC == 0) {
        printf ("               \n")
        printf ("       Convert THEMIS spectral radiance to brightness temperature\n")
        printf ("               \n")
        printf ("       usage: btemp = rad3tb(radiance, band_list)\n")
        printf ("               \n")
        printf ("       where:  radiance = spectral radiance array (e.g. .spectral_qube.data in RDR structure)\n")
        printf ("               band_list = list of bands (e.g. .band_bin.band_bin_band_number array in RDR structure) \n")
        printf ("               band_list is dimensioned (n, 1, 1), where n is the number of bands in the array\n")
        printf ("               \n")
        printf ("               returns btemp array of same dimension as radiance with bands given in band_list\n")
        printf ("               \n")
        printf ("       examples:  btemp = rad3tb(a.spectral_qube.data, a.spectral_qube.band_bin.band_bin_band_number)        \n")
        printf ("                  (where a is RDR structure loaded using davinci 'load_pds' function)\n")
        printf ("               \n")
        printf ("                  btemp = rad3tb(rad, cat(1,2,3,4,5,6,7,8,9,10, axis=x))        \n")
        printf ("               \n")
        printf ("                  btemp = rad3tb(rad[,,9], 9)        \n")
        printf ("                  (where rad is a 10-band spectral radiance array and you want to compute band 9)\n")
        printf ("                  (returns 1 band array) \n")
        printf ("               \n")
        printf ("       Reads in temp_rad_vn look-up table and calls radtotb to do the work     \n")
        printf ("       p. christensen 1/02     \n")
        return(0)
}

# p. christensen 4/17/02
# convert rad (spectral radiance) in .hdf file to brightness temperature

# NsG, Thu Oct 16 15:35:14 MST 2003
# modified to reuse rad to cut down on memory usage.

rad = $1
# changed - 8/30/02  prc
# reorganize band_list from (n,1,1) in RDR to (1,n,1) that is used in radtotb
band_list = translate($2,x,y)

# get temp to rad conversion table
temp_rad = read($DV_SCRIPT_FILES+"/instrument_parameters/temp_rad_v4")

size_temp_rad = dim(temp_rad)

# select correct bands for temp_rad conversion
size = dim(rad)
temp_rad_new = create(size[3]+1, size_temp_rad[2], size_temp_rad[3], format=float)
temp_rad_new[1] = temp_rad[1]
for(i=1; i<= size[3]; i+=1) {
        printf(" load temp_rad with band %d\n", band_list[,i])
        temp_rad_new[i+1,,] = temp_rad[band_list[,i]+1,,]
}

# convert input spectral radiance to brightness temperature
# NsG - reuse the rad variable to cut down on memory usage.

temp_rad=temp_rad_new
d1=dim(rad)[1]
d2=dim(rad)[2]
d3=dim(rad)[3]
printf(" radtotb:  dims = %d %d %d\n", d1, d2, d3)
for(i=1; i<=d3; i+=1) {
        index = i+1
        rad[,,i] = interp(temp_rad[1], temp_rad[index], rad[,,i])
}

#removed dependence on old radtotb function CSE
#rad = radtotb(temp_rad_new, rad)

return(rad)

}

-------

radtotb

**Comment by rfergason** [comment]
Code for rad3rb is copied below.  This may be more than you want....

define rad3tb() {
#Added instrument_parameters to $DV_SCRIPT_FILES support - 1-30-09

if ($ARGC == 0) {
        printf ("               \n")
        printf ("       Convert THEMIS spectral radiance to brightness temperature\n")
        printf ("               \n")
        printf ("       usage: btemp = rad3tb(radiance, band_list)\n")
        printf ("               \n")
        printf ("       where:  radiance = spectral radiance array (e.g. .spectral_qube.data in RDR structure)\n")
        printf ("               band_list = list of bands (e.g. .band_bin.band_bin_band_number array in RDR structure) \n")
        printf ("               band_list is dimensioned (n, 1, 1), where n is the number of bands in the array\n")
        printf ("               \n")
        printf ("               returns btemp array of same dimension as radiance with bands given in band_list\n")
        printf ("               \n")
        printf ("       examples:  btemp = rad3tb(a.spectral_qube.data, a.spectral_qube.band_bin.band_bin_band_number)        \n")
        printf ("                  (where a is RDR structure loaded using davinci 'load_pds' function)\n")
        printf ("               \n")
        printf ("                  btemp = rad3tb(rad, cat(1,2,3,4,5,6,7,8,9,10, axis=x))        \n")
        printf ("               \n")
        printf ("                  btemp = rad3tb(rad[,,9], 9)        \n")
        printf ("                  (where rad is a 10-band spectral radiance array and you want to compute band 9)\n")
        printf ("                  (returns 1 band array) \n")
        printf ("               \n")
        printf ("       Reads in temp_rad_vn look-up table and calls radtotb to do the work     \n")
        printf ("       p. christensen 1/02     \n")
        return(0)
}

# p. christensen 4/17/02
# convert rad (spectral radiance) in .hdf file to brightness temperature

# NsG, Thu Oct 16 15:35:14 MST 2003
# modified to reuse rad to cut down on memory usage.

rad = $1
# changed - 8/30/02  prc
# reorganize band_list from (n,1,1) in RDR to (1,n,1) that is used in radtotb
band_list = translate($2,x,y)

# get temp to rad conversion table
temp_rad = read($DV_SCRIPT_FILES+"/instrument_parameters/temp_rad_v4")

size_temp_rad = dim(temp_rad)

# select correct bands for temp_rad conversion
size = dim(rad)
temp_rad_new = create(size[3]+1, size_temp_rad[2], size_temp_rad[3], format=float)
temp_rad_new[1] = temp_rad[1]
for(i=1; i<= size[3]; i+=1) {
        printf(" load temp_rad with band %d\n", band_list[,i])
        temp_rad_new[i+1,,] = temp_rad[band_list[,i]+1,,]
}

# convert input spectral radiance to brightness temperature
# NsG - reuse the rad variable to cut down on memory usage.

temp_rad=temp_rad_new
d1=dim(rad)[1]
d2=dim(rad)[2]
d3=dim(rad)[3]
printf(" radtotb:  dims = %d %d %d\n", d1, d2, d3)
for(i=1; i<=d3; i+=1) {
        index = i+1
        rad[,,i] = interp(temp_rad[1], temp_rad[index], rad[,,i])
}

#removed dependence on old radtotb function CSE
#rad = radtotb(temp_rad_new, rad)

return(rad)

}

**Comment by rfergason** [comment]
Code for tb2rad is copied below.

Code converts brightness temperature to radiance.

define tb2rad() {
if ($ARGC == 0) {
  printf ("\n");
  printf ("convert temperature to spectral radiance (W cm-1 str-1 micron-1) \n");
  printf ("\n");
  printf ("usage: rad = tbtorad(temp_rad_array, temp_array (K))\n");
  printf ("\n");
  printf ("examples: rad = tbtorad(temp_rad, t)  \n");
  printf ("     where t is (1, 1, 10) array of temps\n");
  printf (" \n");
  printf ("rad = tbtorad(temp_rad, clone(250., 1, 1, 10))        \n");
  printf ("\n");
  printf ("Note: read in: temp_rad = read('/themis/calib/temp_rad_v4')\n");
  printf ("\n");
  printf ("Note:  t can be less than 10 bands if temp_rad array has been adjusted to only\n");
  printf ("       contain the bands used        \n");
  return(0);
}

# p. christensen  10/2/01

 temp_rad = $1;
 temp = $2;

 d1=dim(temp)[1];
 d2=dim(temp)[2];
 d3=dim(temp)[3];
 printf("tbtorad: dims = %d %d %d\n", d1, d2, d3);

 rad = temp * 0.;

 for(i=1; i<=d3; i+=1) {
   index = i+1;
   rad[,,i] = interp(temp_rad[index], temp_rad[1], temp[,,i]);
 }

# clean up
 temp = 0.;

 return(rad);
}

**Comment by jlaura** [comment]
rad3tb
```
define rad3tb() {                                                               
#Added instrument_parameters to $DV_SCRIPT_FILES support - 1-30-09              
                                                                                
if ($ARGC == 0) {                                                               
    printf ("       \n")                                                        
    printf ("   Convert THEMIS spectral radiance to brightness temperature\n")  
    printf ("       \n")                                                        
    printf ("   usage: btemp = rad3tb(radiance, band_list)\n")                  
    printf ("       \n")                                                        
    printf ("   where:  radiance = spectral radiance array (e.g. .spectral_qube.data in RDR structure)\n")
    printf ("           band_list = list of bands (e.g. .band_bin.band_bin_band_number array in RDR structure) \n")
    printf ("           band_list is dimensioned (n, 1, 1), where n is the number of bands in the array\n")
    printf ("           \n")                                                    
    printf ("       returns btemp array of same dimension as radiance with bands given in band_list\n")
    printf ("           \n")                                                    
    printf ("   examples:  btemp = rad3tb(a.spectral_qube.data, a.spectral_qube.band_bin.band_bin_band_number)        \n")
    printf ("          (where a is RDR structure loaded using davinci 'load_pds' function)\n")
    printf ("       \n")                                                        
    printf ("              btemp = rad3tb(rad, cat(1,2,3,4,5,6,7,8,9,10, axis=x))        \n")
    printf ("       \n")                                                        
    printf ("              btemp = rad3tb(rad[,,9], 9)        \n")              
    printf ("          (where rad is a 10-band spectral radiance array and you want to compute band 9)\n")
    printf ("          (returns 1 band array) \n")                              
    printf ("       \n")                                                        
    printf ("   Reads in temp_rad_vn look-up table and calls radtotb to do the work \n")
    printf ("   p. christensen 1/02 \n")                                        
    return(0)                                                                   
}                                                                               
                                                                                
# p. christensen 4/17/02                                                        
# convert rad (spectral radiance) in .hdf file to brightness temperature        
                                                                                
# NsG, Thu Oct 16 15:35:14 MST 2003                                             
# modified to reuse rad to cut down on memory usage.                            
                                                                                
rad = $1                                                                        
# changed - 8/30/02  prc                                                        
# reorganize band_list from (n,1,1) in RDR to (1,n,1) that is used in radtotb   
band_list = translate($2,x,y)                                                   
                                                                                
# get temp to rad conversion table                                              
temp_rad = read($DV_SCRIPT_FILES+"/instrument_parameters/temp_rad_v4")          
                                                                                
size_temp_rad = dim(temp_rad)                                                   
                                                                                
# select correct bands for temp_rad conversion                                  
size = dim(rad)                                                                 
temp_rad_new = create(size[3]+1, size_temp_rad[2], size_temp_rad[3], format=float)
temp_rad_new[1] = temp_rad[1]                                                   
for(i=1; i<= size[3]; i+=1) {                                                   
        printf(" load temp_rad with band %d\n", band_list[,i])                  
        temp_rad_new[i+1,,] = temp_rad[band_list[,i]+1,,]                       
}                                                                               
                                                                                
# convert input spectral radiance to brightness temperature                     
# NsG - reuse the rad variable to cut down on memory usage.                     
                                                                                
temp_rad=temp_rad_new                                                           
d1=dim(rad)[1]                                                                  
d2=dim(rad)[2]                                                                  
d3=dim(rad)[3]                                                                  
printf(" radtotb:  dims = %d %d %d\n", d1, d2, d3)                              
for(i=1; i<=d3; i+=1) {                                                         
        index = i+1                                                             
        rad[,,i] = interp(temp_rad[1], temp_rad[index], rad[,,i])               
}                                                                               
                                                                                
#removed dependence on old radtotb function CSE                                 
#rad = radtotb(temp_rad_new, rad)                                               
                                                                                
return(rad)                                                                     
                                                                                
} 
```
