### ISSUE TITLE
Extract Bands 3 and 9 from rad image

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/themis_ra#33]
The radiance image produced from processing **should** produce a radiance image with all bands. Bands 3 and 9 first need to be extracted.

DoD: Numpy array containing bands 3 and 9

**Comment by jlaura** [comment]
@acpaquette Assigned because I think that you have this covered already (once the PR is merged?)  If not, feel free to unassign.

**Comment by AustinSanders** [comment]
@acpaquette Is this issue ready to be closed?

**Comment by acpaquette** [comment]
Yes, this is also ready to close.
