### ISSUE TITLE
Compute Rock3 and Rock9

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/themis_ra#35]
Generate 2 radiance images given a constant temperature using tb3rad.  Can just 250 be passed in as a constant temperature and can a constant result come back out?

## Acceptance 
- [x] ndarray for R3
- [x] ndarray for R9

**Comment by acpaquette** [comment]
Two questions about this, first I don't see a tb3rad but tb2rad2 seems to do this, so is that what we want to use? Second, what do you mean by generate 2 radiance images?

Currently, tb2rad2 is outputing:
1x1x10 array
0.000173866	

0.000173866	

0.000266925	

0.000310375	

0.000352625	

0.000382479	

0.000396245	

0.000398744	

0.000393225	

0.000348427

This is for passing in 250 and themis as tb2rad2 takes in a temp and an instrument. I am guessing that the 3rd and 9th values are for bands 3 and 9, but how would we generate an image with those? (I could just be miss understanding the issue entirely)

**Comment by jlaura** [comment]
I think this looks good.  @rfergason ?

Would
```
three = np.empty(temperature.shape)
three.fill(some_value)
```
work?

**Comment by AustinSanders** [comment]
@acpaquette should this be closed as well? I think #40 addressed this issue, but it's still open.

**Comment by acpaquette** [comment]
Yes, this should be closed.
