### ISSUE TITLE
Implement a cost function for use in a heuristic

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/themis_ra#36]
Minimize z = abs([delta_{rr} * alpha + delta_{fr} * (1-alpha)] - obs )

s.t.
160 <= rf3 < 250
160 <- rf9 < 250
alphaR + alphaF = 1

**Comment by jlaura** [comment]
Inside of rad3tb is the instrument response to be able to compute the radiance in band 9 knowing the radiance of band 3 (or vice versa).

**Comment by jlaura** [comment]
Here is a super basic implementation of the optimization that I am imagining.  This would need to be applied for each pixel in the input image.  The below picks random numbers of obs3, obs9, r3, and r9.

```python
from scipy.optimize import differential_evolution

def costfunc(variables, obs3, obs9, rock3, rock9):
    alpha = variables[0]
    fine3 = variables[1]
    fine9 = variables[2]
    if fine9 < fine3:
        return 1e10
    delta_obs = abs(obs3 - obs9)
    delta_rock = abs(rock3 - rock9)
    #fine9 = f(fine3)
    delta_fine = abs(fine3 - fine9)
    z = abs((delta_rock * alpha + delta_fine * (1-alpha)) - delta_obs)
    return z

obs3 = 100
obs9 = 150
r3 = 125
r9 = 130

bounds = [(0,1),  # Alpha
          (160, 250), # Fine3
          (160, 250)] # Fine9

res = differential_evolution(costfunc,bounds, args=(obs3, obs9, r3, r9), strategy='best1bin')
alpha, fine3, fine9 = res['x']
print(alpha*100,(1-alpha)*100, fine3, fine9, res['fun'])
```

**Comment by AustinSanders** [comment]
@jlaura @rfergason  I'm working on getting this put in place.  I want to make sure I understand the algorithm properly...  Is it true to say that obs3 and obs9 are the values of pixels that we're reading and that r3 and r9 are constants?  In other words, which of the values [obs3, obs9, r3, r9] are constants and which are the values of pixels that we've read?  I might be misinterpreting this algorithm entirely, so I need a little guidance.

**Comment by jlaura** [comment]
@AustinSanders yes. The obs variables are the ones that are observed from the image. For now, r3 and r9 are the constants from @acpaquette. In the future the r3 and r9 numbers will be variables.
