### ISSUE TITLE
Surface emissivity - 100 m/pxl

### ISSUE THREAD

**Issue by rfergason** [USGS-Astrogeology/themis_ra#4]
As a user, I want to know the emissivity of the surface so that I can calculate the surface temperature correctly.

- [x] @rfergason - we need to know where this data lives
- [x] Get the data homogenized

**Comment by rfergason** [comment]
Highest resolution emissivity map I know of is:
/scratch/rfergason/themis_ra/basemaps/TES_surface_emissivity_4_ppd

Downloaded TES Surface Emissivity at 4ppd (15 km/pxl at the equator - yikes!) from http://tes.asu.edu/products/.  

Minimal documentation about the product copied from the above website:
TES Surface Emissivity														
Global surface emissivity maps, in simple cylindrical projection, are available at several resolutions. TES spectral values for 9-35 and 65-100 are stored as the 73 bands (third dimension) of the ISIS and ENVI files. For more information, see Bandfield, 2003.
Reference: Bandfield (2002), Global mineral distributions on Mars, Journal of Geophysical Research, 10.1029/2001JE001510.
Download:															TES_surface_emissivity_1_ppd envi & envi.hdr (18000 KB) isis (18000 KB)															TES_surface_emissivity_2_ppd envi & envi.hdr (72200 KB) isis (72200 KB)															TES_surface_emissivity_4_ppd envi & envi.hdr (289000 KB) isis (289000 KB)

**Comment by jlaura** [comment]
This is on hold until @rfergason determines if we even need emissivity.

**Comment by rfergason** [comment]
We are not going to correct for emissivity for several reasons:
1. The highest resolution emissivity global map we have is from TES at 15 km/pixel.  That spatial scale is disparate enough from THEMIS (100 m/pixel) that we are just as likely to introduce error as remove error.
2. It is very likely that the TES emissivity map assumes that all anisothermality is due to differences in composition, and that assumption is not valid for this application.
