### ISSUE TITLE
Crop and Clip Test Images

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/themis_ra#43]
As a user/dev, I have test images either locally or if small enough within the repository so that I can exercise the algorithm.

I think the best way to do this is to actually modify the [gdal_translate](https://github.com/USGS-Astrogeology/themis_ra/blob/master/themisra/processing/processing.py#L229) call to accept the 
[latlon](https://github.com/USGS-Astrogeology/themis_ra/blob/master/examples/config.json#L21) key in the config.json file.  This way, the code is going to do the clipping and we do not have to worry about it. 

Three test cases (that would each require a different config.json (maybe use the image name plus some number?).

1. THEMIS: I06520011
  * Lat: 18.44 - 18.46 N Lon: 77.39-77.46 E
  * Lat: 18.42 - 18.50 N Lon: 77.56 - 77.61
2. THEMIS: I31379004
  * Lat: 77.16 - 77.24 Lon: 17.83 - 17.89

## Acceptance Criteria
- [x] Three new configuration files added to the repository
- [x] Manual test (local on your box is fine) that the clipping is working for both the input image and the ancillary data

@rfergason will update with the PATHs to the two images.

**Comment by rfergason** [comment]
Full PDS paths for the 2 THEMIS images listed above:

/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10006/data/odtir1_0006/i065xxrdr/I06520011RDR.QUB

/pds_san/PDS_Archive/Mars_Odyssey/THEMIS/USA_NASA_PDS_ODTSDP_100XX/ODTSDP_10029/data/odtir1_0029/i313xxrdr/I31379004RDR.QUB

**Comment by acpaquette** [comment]
Going off of Jay's suggestion I need to know what "reference" and "reference_resolution" should be in the config file. 

A more important question is should cropping the image based on latlon values need to depend on resolution and reference resolution?

**Comment by jlaura** [comment]
Reference and reference image are not applicable here. The change to make is to the latlon key. Pass these in via the configure and then pass those on through to gdal translate.
