### ISSUE TITLE
Atmospheric Opacity

### ISSUE THREAD

**Issue by rfergason** [USGS-Astrogeology/themis_ra#5]
As a user, I want to  know the atmospheric dust opacity of the surface, so that I can calculate the downwelling and upwelling atmospheric contribution to surface temperature.

This concern is more applicable to THEMIS band 3 than THEMIS band 9 (although we will apply this correction to both bands for consistency), as band 9 is transparent to atmospheric dust.

**Comment by rfergason** [comment]
Use montabone that is located at ......

**Comment by jlaura** [comment]
For this work, simply pull the montabone code from the krc_application, read it into memory and clip the data.
